version: '3.8'

services:
  excel-tool:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    volumes:
      # 掛載資料庫目錄，這樣你可以從主機添加Excel檔案
      - ./database:/app/database
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATA_DIR=./database
    restart: unless-stopped
    container_name: excel-analyzer

  # 可選：添加一個 nginx 反向代理 (如果需要的話)
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - excel-tool
  #   restart: unless-stopped
